name: ubuntu-personal-store
version: '0.1'
summary: Snapweb in a WebView
description: Snapweb in a WebView

grade: devel
confinement: devmode

apps:
  ubuntu-personal-store:
    command: ubuntu-personal-store.launcher
    plugs:
      - browser-support
      - network
      - opengl
      - unity7

parts:
  ubuntu-personal-store-qml:
    plugin: dump
    source: .
    stage-packages:
      - gksu:amd64
      - qmlscene:amd64
      - qml-module-qtquick2:amd64
      - qml-module-qtquick-controls:amd64
      - qml-module-ubuntu-web:amd64
    after: [desktop-qt5]

  launcher:
    plugin: dump
    source: .
    organize:
      ubuntu-personal-store.launcher: bin/ubuntu-personal-store.launcher
